version: '2'

volumes:
  db:
  nginx:


services:
  db:
    container_name: typecho_db
    image: mariadb
    restart: always
    volumes:
      - /usr/local/docker_typecho/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=typecho
      - MYSQL_DATABASE=typecho

  nginx:
    container_name: typecho_web
    image: richarvey/nginx-php-fpm:latest
    restart: always
    links:
      - db
    ports:
      - 80:80
    volumes:
      - /usr/local/docker_typecho/nginx:/etc/nginx/sites-enabled
      - /usr/local/docker_typecho/typecho:/var/www/html